### ISSUE TITLE
Are these two texts from the config screen?

### ISSUE THREAD

**Issue by qznfbnj** [Khajiitos/TradeUses#1]
Strangely, I can't find these two texts https://github.com/Khajiitos/TradeUses/commit/d62d3d9
1.19.2-Forge_43.3.2
tradeuses-1.2.0-1.19.2-FORGE
 
![image](https://github.com/Khajiitos/TradeUses/assets/100760086/84caa922-78c7-4fa0-a9ec-4a1fbf130f72)
![image](https://github.com/Khajiitos/TradeUses/assets/100760086/a411df06-0292-45ed-9562-34f8197b8868)
![image](https://github.com/Khajiitos/TradeUses/assets/100760086/9c01edfe-c589-4c1f-a15c-e0a775202031)

**Comment by Khajiitos** [comment]
Thanks a lot for the translation! I believe those two texts are used for narration only. I thought of including the first text (Trade Uses Config) in the top-middle of the screen, but it would overlap the placeholders text. Either way, I don't think this is an issue, so I will mark it as "won't fix". Thanks again!

**Comment by qznfbnj** [comment]
Oh I got it
