### ISSUE TITLE
Crash when ViaFabricPlus also installed

### ISSUE THREAD

**Issue by YoshiRulz** [Khajiitos/TradeUses#3]
Something to do with `EditBoxMixin`? [Here's the full log](https://hst.sh/utewoxumoy). Easily reproduced by clicking "Direct Connect" in the server list, or by selecting singleplayer when no saves exist.

Doesn't seem to affect ViaFabricPlus 2.x (for Minecraft 1.20.2).

**Comment by Khajiitos** [comment]
Thanks for letting me know! It's just a simple mixin conflict as we both try to allow inserting normally unallowed characters into edit boxes. I will try to approach this problem differently so that it doesn't conflict.

**Comment by Khajiitos** [comment]
This should now be fixed in the 1.2.3 version of this mod (https://github.com/Khajiitos/TradeUses/commit/050988b88161c485d4d28669f0baf7789c385074), available on CurseForge and Modrinth.
