### ISSUE TITLE
Crash with mod 'FancyMenu'

### ISSUE THREAD

**Issue by stlouisn** [Khajiitos/TradeUses#4]
Pretty sure issue is with FancyMenu and not Trade Uses. Reported it on their page. Reference link:

https://github.com/Keksuccino/FancyMenu/issues/711

**Comment by Khajiitos** [comment]
> It's interesting that this mod messes with the trade menu as well. I will investigate this issue later - I'm not fully certain if what I'm looking at is the problem, but from the looks of it this, the crash occurs in my code due to a slight programming mistake, which just happened to never crash without other mods that play with that menu. ![image](https://private-user-images.githubusercontent.com/58109276/307452501-682c8c9a-116d-49a0-ae9a-4f8dfdcdde89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjM0NjIsIm5iZiI6MTcwODcyMzE2MiwicGF0aCI6Ii81ODEwOTI3Ni8zMDc0NTI1MDEtNjgyYzhjOWEtMTE2ZC00OWEwLWFlOWEtNGY4ZGZkY2RkZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIxMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMDgzNDc0OTdmMmM2MWU3MjQ4N2Y1ZjU0M2JhMjIxOTRmZjBkYmYzOWVhMTNhYWVkMmRkNTdjYTk3NDViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.evvBm7Y_QrcyEcxXUdZNDLtq3bj3hZ02AnxMmhoe4z0)

**Comment by Khajiitos** [comment]
This shouldn't happen anymore in the 1.2.4 version of Trade Uses (https://github.com/Khajiitos/TradeUses/commit/f1c3b043c32729c08fb6f21bfd7726a367ad8c53). The issue was with my mod, it just happened to reveal itself with Fancy Menu.

**Comment by stlouisn** [comment]
Thank you for the quick fix. I can confirm this is fixed with Trade Uses version 1.2.4. Love both of your mods btw.

**Comment by V972** [comment]
Can I ask for a backport of this fix for 1.18.2 please? Would really love to use this mod in m modpack 🙏
