### ISSUE TITLE
Mod causes strange behavior with chat window

### ISSUE THREAD

**Issue by daniel-koval** [Khajiitos/TradeUses#6]
With this mod enabled, when I press / to open chat and type a command, or press up arrow to go through chat history, the cursor starts at the beginning of the message.

**Comment by Khajiitos** [comment]
Sorry for responding late, this is caused by a small mistake which to my surprise ended up affecting all edit boxes in the game, by not properly setting the cursor's position when a value is set in an edit box. I figured it out and fixed it, and will upload the fixed mod as version 1.2.5 very soon.
